# SPDX-FileCopyrightText: Â© 2022 Decompollaborate
# SPDX-License-Identifier: MIT

[project]
name = "mapfile_parser"
version = "1.1.3"
description = "Map file parser library focusing decompilation projects"
readme = "README.md"
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://github.com/Decompollaborate/mapfile_parser"
"Bug Tracker" = "https://github.com/Decompollaborate/mapfile_parser/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.cibuildwheel]
skip = ["cp36-*"]
